version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Apigateway/Dockerfile

  authenticationservice:
    image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile


  catalogservice:
    image: ${DOCKER_REGISTRY-}catalogservice
    build:
      context: .
      dockerfile: CatalogService/Dockerfile


  logservice:
    image: ${DOCKER_REGISTRY-}logservice
    build:
      context: .
      dockerfile: LogService/Dockerfile


  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: WebUI/Dockerfile

  
