version: '3.4'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"

  authenticationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"

  
  catalogservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8002:80"


  logservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8003:80"


  webui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8004:80"

  
